### ISSUE TITLE
Pipeline failure

### ISSUE THREAD

**Issue by juanangp** [rest-for-physics/rawlib#74] opened 2022-08-30 08:21 UTC
Pipeline failure in rawlib in stand alone compilation

![image](https://user-images.githubusercontent.com/80903717/187386533-61810a91-7d47-4af3-afa5-22cec6bb6343.png)

It suddenly start failing on `Analysis Process`

![image](https://user-images.githubusercontent.com/80903717/187386970-cda8c9a7-47c9-4673-8a5e-8a31715b6d10.png)

The failure seems related to changes in framework, that I cannot spot.

**Comment by juanangp** [comment] 2022-08-30 09:12
> It is this associated to a particular PR?

I cannot spot the associated PR, but apparently should be related with the dictionary generated on-the-fly on `TRestReflector`

![image](https://user-images.githubusercontent.com/80903717/187398185-81d90e4b-1b61-4a7c-8da2-98075c80e0a9.png)

**Comment by jgalan** [comment] 2022-08-30 12:25
I commented something about at this PR https://github.com/rest-for-physics/rawlib/pull/73

**Comment by juanangp** [comment] 2022-08-30 12:36
> I commented something about at this PR #73

I think the issue was introduced about this time, but not in this PR

I am getting annoyed about this issue, if you compile with rawlib only you get the failure:
```
cmake ../ -DCMAKE_INSTALL_PREFIX=../install -DRESTLIB_RAW=ON
```
But when you compile with detectorlib, the pipeline suceed:
```
cmake ../ -DCMAKE_INSTALL_PREFIX=../install -DRESTLIB_RAW=ON -DRESTLIB_DETECTOR=ON
```
Anyone has a hint of what is going on? The only difference are the dependencies, when detectorlib is ON rawlib is compiled with this dependency `COMPILELIB(deps)`

**Comment by jgalan** [comment] 2022-08-31 08:53
> I think might be related with changes on `startup.cpp` on [rest-for-physics/framework#231](https://github.com/rest-for-physics/framework/pull/231)

The last successful rawlib pipeline validation occured on 19th of June. The PR rest-for-physics/framework#231 was merged on 7th June. 

The problem must come later on.

**Comment by juanangp** [comment] 2022-08-31 09:31
I just realized that before it was creating the dictionary, but it is not doing it anymore.

![image](https://user-images.githubusercontent.com/80903717/187644846-1ac6e8be-6322-40a4-85ad-f18acdeb78e9.png)

I don't understand what is going on but it seems that the generation of the dictionary is required while compiling rawlib stand alone but it is not required anymore while detectorlib dependencies are required. Does anyone has any insight?

**Comment by jgalan** [comment] 2022-08-31 09:56
> I just realized that before it was creating the dictionary, but it is not doing it anymore.
> 
Thats what I mentioned at https://github.com/rest-for-physics/rawlib/pull/73

**Comment by jgalan** [comment] 2022-08-31 10:08
I believe after the following PR it is not passing rawlib pipeline https://github.com/rest-for-physics/framework/pull/263

Inside the framework repository `git checkout d42b180` will fail the validation, while `git checkout 74061eb` will succeed the validation.

Those commits correspond to PR rest-for-physics/framework#263 and rest-for-physics/framework#262

**Comment by jgalan** [comment] 2022-09-01 09:33
Finally it was https://github.com/rest-for-physics/framework/pull/244

**Comment by lobis** [comment] 2022-09-05 10:28
I think the problem is not fixed yet by https://github.com/rest-for-physics/framework/pull/289 as you can see from https://github.com/rest-for-physics/rawlib/actions/runs/2992398834, which was run after merging the solution.

**Closed** 2022-09-05 11:17 UTC
Labels: bug
